- hosts: minion
  connection: local
  roles:
    - common
    - swap
    - docker
    - aws_ecs
- hosts: controller
  connection: local
  roles:
    - common
    - swap
    - docker
    - empire
- hosts: empire_ami
  connection: local
  roles:
    - {role: build_ami, tags: ['build_ami']}
    - common
    - docker
    - aws_ecs
    - empire
